name: Submit Application to B12

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your full name"
        required: true
      email:
        description: "Your email address"
        required: true
      resume_link:
        description: "Link to your resume (PDF, HTML, LinkedIn, etc.)"
        required: true
      secret:
        description: "Signing secret "
        required: true

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Submit to B12
        env:
          NAME: ${{ inputs.name }}
          EMAIL: ${{ inputs.email }}
          RESUME_LINK: ${{ inputs.resume_link }}
          REPOSITORY_LINK: ${{ github.server_url }}/${{ github.repository }}
          SECRET: ${{ inputs.secret }}
        run: python submit_application.py
